---
apiVersion: v1
kind: Service
metadata:
  name: javawebappliveservice
spec:
  type: LoadBalancer
  selector:
    version: v1
  ports:
  - port: 5555
    targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendbluedeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-Backend-app
      version: v1
      color: blue
  template:
    metadata:
      name: node-Backend-app
      labels:
        app: node-Backend-app
        version: v1
        color: blue
    spec:
      containers:
      - name: nodeappcontainers
        image: dockerdocker2023/backendjenkinsss
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
